// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Fallingnote",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Fallingnote",
            targets: ["AppModule"],
            bundleIdentifier: "ds.ColorKey",
            teamIdentifier: "U2Y4UHZS79",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .musicGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Sound/GameOver.wav"),
                .copy("Sound/do.mp3"),
                .copy("Sound/re.mp3"),
                .copy("Sound/mi.mp3"),
                .copy("Sound/fa.mp3"),
                .copy("Sound/sol.mp3"),
                .copy("Sound/la.mp3"),
                .copy("Sound/si.mp3"),
                .copy("Sound/ButtonClick.mp3")
            ]
        )
    ]
)
